//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintContract1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoanEntities8 : DbContext
    {
        public LoanEntities8()
            : base("name=LoanEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblBranch> tblBranches { get; set; }
        public virtual DbSet<tblCostomer> tblCostomers { get; set; }
        public virtual DbSet<tblHesab> tblHesabs { get; set; }
        public virtual DbSet<tblPardakhtAghsat> tblPardakhtAghsats { get; set; }
        public virtual DbSet<tblVam> tblVams { get; set; }
    }
}
