//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintContract1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranch
    {
        public long Id { get; set; }
        public string BrName { get; set; }
        public string BrCode { get; set; }
        public string BrAddress { get; set; }
        public Nullable<long> AccountId { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
