//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintContract1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCostomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCostomer()
        {
            this.tblHesabs = new HashSet<tblHesab>();
        }
    
        public long Id { get; set; }
        public string CodeMeli { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string FatherName { get; set; }
        public string DateOfBirth { get; set; }
        public string NumberOfShenasname { get; set; }
        public string SeryalOfShenasname { get; set; }
        public string MahalSodour { get; set; }
        public string Tell { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string CodePosti { get; set; }
        public string Email { get; set; }
        public string Jender { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHesab> tblHesabs { get; set; }
    }
}
