//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintContract1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHesab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHesab()
        {
            this.tblVams = new HashSet<tblVam>();
        }
    
        public long Id { get; set; }
        public string HesabNumber { get; set; }
        public string HesabType { get; set; }
        public Nullable<long> Mojodi { get; set; }
        public Nullable<long> CostomerId { get; set; }
        public Nullable<long> CostomerHoghoghiId { get; set; }
    
        public virtual tblCostomer tblCostomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVam> tblVams { get; set; }
    }
}
